services:
  web-app:
    build:
        context: .  # папка, в которой находится Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./financial_app:/financial_app
      # - ./db.sqlite3:/db.sqlite3
      # - db-data:/db.sqlite3
      - db-data:/financial_managment
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=django-insecure-f-8xu69=^v3gzp06xwim2ek=hbu=rv*q8c982(_f!h32%f5xu2
      - DEBUG=1
      - API_KEY=f6507751e405811c5c6e915f57406bff
      - BROKER_URL=redis://redis:6379/0
      - CACHES_LOCATION=redis://redis:6379
    depends_on:
      - redis

  celery:
    build:
      context: .
    command: celery -A financial_managment worker -l info -P solo
    volumes:
      - ./financial_app:/financial_app
      - db-data:/financial_managment
    environment:
      - SECRET_KEY=django-insecure-f-8xu69=^v3gzp06xwim2ek=hbu=rv*q8c982(_f!h32%f5xu2
      - DEBUG=1
      - API_KEY=f6507751e405811c5c6e915f57406bff
      - BROKER_URL=redis://redis:6379/0
      - CACHES_LOCATION=redis://redis:6379
    depends_on:
      - web-app
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A financial_managment beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./financial_app:/financial_app
      - db-data:/financial_managment
    environment:
      - SECRET_KEY=django-insecure-f-8xu69=^v3gzp06xwim2ek=hbu=rv*q8c982(_f!h32%f5xu2
      - DEBUG=1
      - API_KEY=f6507751e405811c5c6e915f57406bff
      - BROKER_URL=redis://redis:6379/0
      - CACHES_LOCATION=redis://redis:6379
    depends_on:
      - web-app
      - redis

  redis:
    image: redis:alpine  # Use the lightweight Redis image
    ports:
      - 6379:6379

volumes:
  db-data:
