# Generated by Django 4.2.11 on 2024-03-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('NUTRITION', 'Nutrition'), ('PUBLIC UTILITIES', 'Public utilities'), ('PURCHASES', 'Purchases'), ('FAMILY', 'Family'), ('TRANSPORT', 'Transport'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('PRESENT', 'Present'), ('INVESTMENTS', 'Investments'), ('OTHER EXPENSES', 'Other expenses')], max_length=256),
        ),
    ]
