# Generated by Django 4.2.11 on 2024-03-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0004_alter_userprofile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='account',
            field=models.FloatField(default=0.0),
        ),
    ]
