# Generated by Django 4.2.11 on 2024-03-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0008_operation_operation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
