# Generated by Django 4.2.11 on 2024-03-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0009_remove_budget_category_remove_operation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_category',
            field=models.CharField(blank=True, choices=[('NUTRITION', 'Nutrition'), ('PUBLIC UTILITIES', 'Public utilities'), ('PURCHASES', 'Purchases'), ('FAMILY', 'Family'), ('TRANSPORT', 'Transport'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('PRESENT', 'Present'), ('INVESTMENTS', 'Investments'), ('OTHER EXPENSES', 'Other expenses')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_category',
            field=models.CharField(blank=True, choices=[('NUTRITION', 'Nutrition'), ('PUBLIC UTILITIES', 'Public utilities'), ('PURCHASES', 'Purchases'), ('FAMILY', 'Family'), ('TRANSPORT', 'Transport'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('PRESENT', 'Present'), ('INVESTMENTS', 'Investments'), ('OTHER EXPENSES', 'Other expenses')], max_length=256, null=True),
        ),
    ]
