# Generated by Django 4.2.11 on 2024-04-02 13:22

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0012_userprofile_balance_userprofile_balance_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=10, null=True),
        ),
    ]
