# Generated by Django 4.2.11 on 2024-04-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0013_alter_userprofile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='account',
        ),
    ]
