# Generated by Django 4.2.11 on 2024-04-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0015_budget_balance_budget_balance_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='account',
        ),
    ]
