# Generated by Django 4.2.11 on 2024-04-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0016_remove_budget_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
