# Generated by Django 4.2.11 on 2024-04-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0017_budget_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='balance_currency',
        ),
    ]
