# Generated by Django 4.2.11 on 2024-04-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0018_remove_budget_balance_remove_budget_balance_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={},
        ),
        migrations.RemoveField(
            model_name='operation',
            name='created',
        ),
    ]
