# Generated by Django 4.2.11 on 2024-04-06 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0019_alter_operation_options_remove_operation_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created_at',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
