# Generated by Django 4.2.11 on 2024-05-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0020_operation_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='operation',
            name='currency',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount_of_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
