# Generated by Django 4.2.11 on 2024-06-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0021_alter_operation_options_operation_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='currency',
        ),
    ]
